# Generated by Django 4.2.3 on 2024-03-18 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=40)),
                (
                    "followers",
                    models.ManyToManyField(
                        related_name="followed_by", to="twitter.user"
                    ),
                ),
                (
                    "follows",
                    models.ManyToManyField(related_name="following", to="twitter.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
