# Generated by Django 4.2.3 on 2024-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followed_by", to="twitter.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="following", to="twitter.user"
            ),
        ),
    ]
