# Generated by Django 4.2.3 on 2024-03-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0003_alter_user_followers_alter_user_follows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tweets",
            field=models.ManyToManyField(
                blank=True, related_name="authors", to="twitter.tweet"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followed_by", to="twitter.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="following", to="twitter.user"
            ),
        ),
    ]
