# Generated by Django 4.2.3 on 2024-03-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("twitter", "0006_alter_tweet_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tweets",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followers_set", to="twitter.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="following_set", to="twitter.user"
            ),
        ),
    ]
