# Generated by Django 4.2.3 on 2024-03-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0007_remove_user_tweets_alter_tweet_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="twitter.user"
            ),
        ),
    ]
