# Generated by Django 4.2.3 on 2024-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0008_alter_tweet_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
