# Generated by Django 4.2.3 on 2024-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0012_alter_message_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
