# Generated by Django 4.2.3 on 2024-04-04 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0013_alter_conversation_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
    ]
