# Generated by Django 4.1.4 on 2024-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="", max_length=100),
        ),
    ]
